[package]
name = "rpush"
version = "0.0.2"
edition = "2021"
authors = ["Liyan 18525589998@163.com"]
description = "push files to server space."
license = "MIT"
documentation = "https://docs.rs/rpush"
homepage = "https://www.surcode.cn/docs/apps/rpush"
repository = "https://github.com/ennriaaa/rpush/"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.21", features = ["derive"] }
serde = { version = "1.0.144", features = ["derive"] }
nu-ansi-term = { version = "0.46.0" }

[dependencies.confy]
features = ["yaml_conf"]
default-features = false